- Test/src/main/webapp/WEB-INF/index.jsp
PR 테스트 진행중
- 최초 branch 생성(develop, ksk)
- 최초 PR 진행
> [ksk] index 최초 commit

- Test/src/main/webapp/WEB-INF/index.jsp
> [develop] branch 생성을 위한 최초 commit

- Test/src/main/webapp/WEB-INF/ksk.jsp
> [ksk] branch check

- Test/.gitignore
- Test/src/main/webapp/WEB-INF/index.jsp
- Test/src/main/webapp/WEB-INF/web.xml
Develop -> Master Branch 최초 PR 진행.
> Develop -> Master Branch 최초 PR

- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateMoveServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateSelectServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/LoginEndServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/loginServlet.java
- lumodiem/src/main/java/com/lumodiem/account/dao/AccountDao.java
- lumodiem/src/main/java/com/lumodiem/account/service/AccountService.java
- lumodiem/src/main/java/com/lumodiem/account/vo/Account.java
- lumodiem/src/main/java/com/lumodiem/common/filter/EncryptFilter.java
- lumodiem/src/main/java/com/lumodiem/common/filter/PassWordEncodingWrapper.java
- lumodiem/src/main/resources/mappers/account-mapper.xml
- lumodiem/src/main/resources/mybatis-config.xml
- lumodiem/src/main/webapp/index.jsp
- lumodiem/src/main/webapp/views/account/create.jsp
- lumodiem/src/main/webapp/views/account/createSelect.jsp
- lumodiem/src/main/webapp/views/account/login.jsp
- lumodiem/src/main/webapp/views/include/header.jsp
- lumodiem/src/main/webapp/views/include/nav.jsp
- lumodiem/src/main/webapp/views/jquery-3.7.1.js
[ksk] index 페이지에 nav 적용해서 이동 기능만 추가 완료.
부트스트랩 적용 전이라 a태그로 url만 적용해놨음.
index 페이지 수정
decleration tag -> c : import tag로 수정
[ksk] LumoDiem 기능 구현
- 회원가입 기능 구현 완료(중복검사, 정규식 검사 미완성)
- 로그인 기능 구현 완료(암호화 완료)
- 회원의 grade에 알맞는 nav메뉴 출력 및 url 구현 완료
- 이슈 : jQuery 파일이 source folder 하위에 위치시 참조가 안됨
> [ksk] LumoDiem 기능 구현(회원가입, 로그인)

- lumodiem/src/main/webapp/index.jsp
- lumodiem/src/main/webapp/views/account/create.jsp
[ksk] 페이지명 수정 및 회의 이후 commit
회의 이후 페이지명 수정, DB 관련 공지 완료.
driver.properties는 slack 통해서 전달 드리겠습니다.
> [ksk] 페이지명 수정 및 회의 이후 commit

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/InsertReviewPageServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewBoardServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/ReviewCmt.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/ReviewLike.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/ReviewMapping.java
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
Review.vo 완성.
Review 게시글 작성중입니다
> Lyj 리뷰게시글 작성중

- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Chat.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassDate.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassLike.java
> [cya] klass vo annotation 추가 commit

- lumodiem/src/main/webapp/views/test01/test01.jsp
Ksk 부트스트랩 테스트 진행중
- nav 완성
- board에 쓸 구성 진행중
> Ksk 부트스트랩 테스트 진행중

- lumodiem/src/main/webapp/index.jsp
- lumodiem/src/main/webapp/views/include/nav.jsp
- lumodiem/src/main/webapp/views/test01/test01.jsp
[[ksk] nav, index bootstrap 적용 완료]
> [ksk] nav, index bootstrap 적용 완료

- lumodiem/src/main/java/com/lumodiem/account/controller/LoginServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/LogoutServlet.java
- lumodiem/src/main/webapp/index.jsp
- lumodiem/src/main/webapp/views/account/create.jsp
- lumodiem/src/main/webapp/views/account/createSelect.jsp
- lumodiem/src/main/webapp/views/bootTest/test01.jsp
- lumodiem/src/main/webapp/views/include/nav.jsp
[ksk] nav, index 분리 완료
- nav, index 분리 완료(주의 : include시 index에서는 아래에 그 외의 jsp에서는 title 밑에 하면 됩니다.)
- logout 기능 구현
> [ksk] nav, index 분리 완료, logout 기능 구현

- lumodiem/src/main/java/com/lumodiem/account/controller/LoginServlet.java
[ksk] loginServlet 다시 commit
- 팀원들 loginServlet 부재로 다시 commit 해봤습니다.
> [ksk] loginServlet 다시 commit

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardCreateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardCreateServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardListServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Klass.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardCreate.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardList.jsp
[cya] klassBoardCreate 게시글 등록 jsp, mapper, servlet 수정 완료 commit
> 주최자 게시글 등록 수정 완료

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/UpdateReviewEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/review/insertReview.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
- lumodiem/src/main/webapp/views/review/updateReview.jsp
[lyj]
reviewBoard.jsp 수정
리뷰 게시판 들어갈때 게스트는 입장불가 하게 만들었음.
리뷰 게시글 수정페이지 작성중
> Lyj 리뷰보드 수정 , 리뷰게시글 수정페이지 작성중

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewBoardServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/review/insertReview.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
lyj
리뷰게시글 목록조회 추가
리뷰게시글 검색기능 추가
리뷰게시글 추가기능 작업중
> [lyj] 리뷰 게시판

- lumodiem/src/main/webapp/views/review/insertReview.jsp
> [lyj] 리뷰게시글 작성 페이지 완료

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewBoardServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/review/insertReview.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
- 게시글 목록조회 시 닉네임까지 보이게 추가
- 게시글 검색 시 닉네임도 검색 가능하게 기능추가
- 리뷰 게시글 추가시 홈화면 말고 리뷰 게시글 목록조회로 돌아가게 수정
> [lyj] 게시글 목록조회 수정, 리뷰게시글 추가페이지 수정

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewBoardServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
lyj
- reviewVo 에서 reviewRegDate,reviewModDate 추가 
- 데이터베이스에도 추가 완료
- 리뷰 목록 조회 최신순/오래된순 정렬 버튼 추가
> Lyj reviewVo 추가 ,리뷰목록조회 최신순/오래된순 추가

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/InsertReviewPageEndServlet.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
lyj
- 리뷰게시글 추가 작성완료
- reg_date, mod_date 추가함
> [lyj] 리뷰 게시글 추가 reg_date,mod_date 추가

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
LYJ
- 리뷰게시판 입장시 게스트는 입장불가
- confirm 기능으로 로그인페이지로 이동하시겠습니까 
-  (예 => 로그인페이지, 아니요 => 홈화면)
- 게시글 상세조회 페이지 완료
- reviewBoard.jsp 에서 수정삭제기능 삭제 후
- 상세조회 페이지에 넣었음
> Lyj 리뷰게시글 상세조회 완료

- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageLikeServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassLike.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/ReviewLike.java
- lumodiem/src/main/java/com/lumodiem/common/secure/SecureCode.java
- lumodiem/src/main/webapp/views/mypage/hostmypagelike.jsp
[ksk] host mypage 작업중1 2025-02-28
- 좋아요 목록 조회(작성중)
- klassVo, reviewVo 필드에 추가로 우선 PR 올립니다.
> [ksk] host mypage 작업중. 좋아요 목록 조회 페이지 작성중. DB 컬럼 제약조건 변경

- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageLikeServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/account/dao/HostMypageDao.java
- lumodiem/src/main/java/com/lumodiem/account/service/HostMypageService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassLike.java
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/resources/mybatis-config.xml
- 좋아요 목록 조회(작성중 mapper, mybatis-config 완료 -> jsp 작성중)
- mybatis-config 수정으로 PR 올립니다.
> [ksk] host mypage 작업중. mybatis-config 수정으로 PR 올립니다.

- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Klass.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/InsertReviewPageEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/InsertReviewPageServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/review/insertReview.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
> Lyj 리뷰 게시글 추가 페이지 완성

- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateMoveServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateSelectServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageCmt.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageLikeServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/LoginServlet.java
- lumodiem/src/main/java/com/lumodiem/account/service/HostMypageService.java
- lumodiem/src/main/java/com/lumodiem/common/filter/PassWordEncodingWrapper.java
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/webapp/views/mypage/hostmypagelike.jsp
[ksk] host mypage 작업중5 2025-02-28
- 좋아요 목록 조회 완료(임시)
- 로그인, 회원가입 페이지 로그인시 못 들어가게 막아둠
- DB FK 리뷰게시판의 (클래스 예약일 목록 번호 컬럼 삭제)
> [ksk] 좋아요 목록 조회 완료. 로그인,회원가입페이지 막아둠. 컬럼 제약조건 변경. DB 컬럼 삭제

- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- 좋아요 목록 조회 완료(임시)
- 로그인, 회원가입 페이지 로그인시 못 들어가게 막아둠
- DB FK 리뷰게시판의 (클래스 예약일 목록 번호 컬럼 삭제)
- 컬럼 삭제 대응하여 ReviewVo 필드 수정, mypage-mapper resultMap 수정
> [ksk] host mypage 작업중 DB 리뷰게시판 컬럼 삭제 대응 완료

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/common/secure/SecureCode.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardCreate.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardUpdate.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
조회 테이블 아래쪽
유저 등급 별 작성 또는 삭제 버튼 반영
> [cya] klassDetail.jsp 조건별 버튼 반영 commit

- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageCmt.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageLikeServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/MemberMypageKlass.java
- lumodiem/src/main/java/com/lumodiem/account/dao/HostMypageDao.java
- lumodiem/src/main/java/com/lumodiem/account/service/HostMypageService.java
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/resources/mybatis-config.xml
- lumodiem/src/main/webapp/views/include/nav.jsp
- lumodiem/src/main/webapp/views/mypage/hostmypagecmt.jsp
- lumodiem/src/main/webapp/views/mypage/hostmypagelike.jsp
- lumodiem/src/main/webapp/views/mypage/membermypage.jsp
- 좋아요 목록 조회 완료(임시)
- 로그인, 회원가입 페이지 로그인시 못 들어가게 막아둠
- DB FK 리뷰게시판의 (클래스 예약일 목록 번호 컬럼 삭제)
- 컬럼 삭제 대응하여 ReviewVo 필드 수정, mypage-mapper resultMap 수정
- host mypage 임시 작업 완료
- 멤버 : 참여 클래스 조회(진행중)
> [ksk] host mypage 임시 작업 완료 + member mypage 작업중1 2025-02-28

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateEndServlet.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoardUpdate.jsp
session 적용 아직임
host가 작성한 게시글 클릭 시 수정버튼 노출
수정 버튼 클릭 시 해당 게시글 정보 노출
이후 수정 버튼 클릭 시 수정된 정보가 게시판에 저장되도록 구현
> [cya] klassBoardUpdate 완료 commit

- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveListServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ApproveDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ApproveSerview.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/CreateCommentEndServlet.java
- lumodiem/src/main/resources/mappers/approve-mapper.xml
- lumodiem/src/main/resources/mybatis-config.xml
- lumodiem/src/main/webapp/views/admin/adminPage.jsp
- lumodiem/src/main/webapp/views/admin/approveList.jsp
- lumodiem/src/main/webapp/views/comment/directSelectComment.jsp
[kty] 관리자 페이지 기능 88.35%
신고된 클래스 o
신고된 리뷰 o
신고된 리뷰 댓글 o
주최자 게시글 목록 (기능 구현중... 50%)
디테일한 작업 필요 기능'만' 구현
> Kty 관리자 페이지 클래스 승인/반려 구현중 ( 50% ) 

- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageApproveKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageCmt.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageLikeServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/MemberMypageKlass.java
- lumodiem/src/main/java/com/lumodiem/account/dao/MypageDao.java
- lumodiem/src/main/java/com/lumodiem/account/service/MypageService.java
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/webapp/views/mypage/membermypageklass.jsp
[ksk] host mypage 임시 작업 완료 + member mypage 작업중2 2025-02-28
- 좋아요 목록 조회 완료(임시)
- 로그인, 회원가입 페이지 로그인시 못 들어가게 막아둠
- DB FK 리뷰게시판의 (클래스 예약일 목록 번호 컬럼 삭제)
- 컬럼 삭제 대응하여 ReviewVo 필드 수정, mypage-mapper resultMap 수정
- 클래스 조회 메소드명 변경 selectApproveListByHostAccountNo -> selectApproveListByAccountNo
- host와 member 모두 사용 가능하기 위함.
- hostMypageService, hostMyPage
- 멤버 : 참여 클래스 조회(50%)
> [ksk] host mypage 임시 작업 완료 + member mypage 작업중2 2025-02-28

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardDeleteServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardUpdate.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 게시글 삭제 confirm 시 취소를 눌러도 삭제 되는것 확인, 오후에 수정 예정입니다.
- delete 완료했음 file과 attach, 세션 정보 확인은 아직임
- klassBoard.jsp 에서 안 쓰는 버튼 삭제 수정 완
- 클래스 게시글 삭제 했을 때, klass_no를 외래키로 쓰는 테이블에서 klass_no가 null로 변경 되는 것 확인 완료
- 게시글 상세조회에서 신고하기 버튼 형태만 만들었음.
- 게시글 수정시 klass테이블에 mod_date 반영해야함
> [cya] KlassBoardDelete 기능 구현 commit 

- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveListServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveUpdateServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/DeleteReportKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/DeleteReportReviewCmtServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/DeleteReportReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ApproveDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ApproveSerview.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/vo/Approve.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/DeleteReviewCommentServlet.java
- lumodiem/src/main/resources/mappers/approve-mapper.xml
- lumodiem/src/main/resources/mybatis-config.xml
- lumodiem/src/main/webapp/views/admin/approveDetail.jsp
- lumodiem/src/main/webapp/views/admin/approveList.jsp
[kty] 관리자 페이지 기능 90%
신고된 클래스 o
신고된 리뷰 o
신고된 리뷰 댓글 o
주최자 게시글 목록 -승인 o-
.                               -반려 x-
디테일한 작업 필요 기능'만' 구현
> Kty 관리자 페이지 기능 90%

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardCreateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassAttach.java
- lumodiem/src/main/java/com/lumodiem/klassfile/FilePathServlet.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/resources/mybatis-config.xml
- lumodiem/src/main/webapp/views/klass/klassBoardCreate.jsp
-klass-mapper 수정
-mybatis-config 수정
-klassBoardCreate 관련 jsp,servlet, service,dao 전부 수정
- file, attach, mapping 데이터 insert 확인 완료
> [cya] klassBoardCreate 완성 commit

- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateDuplicateServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/account/dao/AccountDao.java
- lumodiem/src/main/java/com/lumodiem/account/service/AccountService.java
- lumodiem/src/main/java/com/lumodiem/common/sql/SqlSessionTemplate.java
- lumodiem/src/main/resources/mappers/account-mapper.xml
- lumodiem/src/main/webapp/views/account/create.jsp
[ksk] host,member mypage 공통 기능 작업완료. 회원가입 기능2종 완료. 2025-03-02
- 마이페이지 공통 기능 작업 완료(좋아요 누른 클래스, 리뷰 조회 / 내가 작성한 댓글 목록 확인)
- 회원가입시 버그 수정(JQuery 중복 태그 삭제)
- 회원가입 중복 검사 완료.
- 회원가입 정규식 완료.
- DB 컬럼 속성 추가. klass_date 테이블의 klass_count 기본값을 0으로 설정
> [ksk] DB 속성 변경. host,member mypage 공통 기능 작업완료. 회원가입 기능2종 완료.

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Klass.java
- lumodiem/src/main/java/com/lumodiem/klassfile/FilePathServlet.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
-klassfile/FilePathServlet 수정
-klassDetail.jsp 에 img 불러오는 div 작성
-HostBoardService, HostBoardDao 메소드 추가
-klass-mapper의 attachOne, klassAttachList 작성
> [cya] 클래스게시글 상세조회 사진 이미지 불러오기 완료 commit

- lumodiem/.classpath
- lumodiem/.settings/org.eclipse.wst.common.component
- lumodiem/src/main/java/com/lumodiem/account/controller/ResetPwServelt.java
- lumodiem/src/main/java/com/lumodiem/account/controller/ResetPwSetPwEndServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/ResetPwSetPwServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/SearchIdEnd.java
- lumodiem/src/main/java/com/lumodiem/account/controller/SearchIdEndServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/SearchIdServlet.java
- lumodiem/src/main/java/com/lumodiem/account/dao/AccountDao.java
- lumodiem/src/main/java/com/lumodiem/account/service/AccountService.java
- lumodiem/src/main/java/com/lumodiem/common/filter/EncryptFilter.java
- lumodiem/src/main/resources/mappers/account-mapper.xml
- lumodiem/src/main/webapp/views/account/create.jsp
- lumodiem/src/main/webapp/views/account/login.jsp
- lumodiem/src/main/webapp/views/account/resetPw.jsp
- lumodiem/src/main/webapp/views/account/resetPwSetPw.jsp
- lumodiem/src/main/webapp/views/account/resetPwSetPwEndSuccess.jsp
- lumodiem/src/main/webapp/views/account/searchId.jsp
- lumodiem/src/main/webapp/views/account/searchIdFail.jsp
- lumodiem/src/main/webapp/views/account/searchIdSuccess.jsp
[ksk] 아이디 찾기, 비밀번호 재설정 기능 완료 2025-03-03
- 아이디 찾기 기능 완료. 
- 비밀번호 찾기 기능 완료. 
- (아이디 찾기, 비밀번호 찾기 성공시 로그인 페이지로 가면 아이디 입력 되어있음)
- 회원가입 주민등록번호 정규식 수정
> [ksk] 아이디 찾기 기능 완료. 비밀번호 재설정 기능 완료. 회원가입 주민등록번호 정규식 수정

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Klass.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoardUpdate.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
[cya] klassBoardDetail 페이지에서 댓글(리뷰) 불러오기 완료
- 게시글 update는 미완성
- 게시글 상세페이지에서 해당 클래스 예약한 회원의 리뷰만 보이게 했으나
- 리뷰 클릭시 리뷰글 상세페이지로 이동하는건 아직 구현 못함.
> [cya] klassBoardDetail 페이지에서 댓글(리뷰) 불러오기 완료

- lumodiem/src/main/java/com/lumodiem/account/vo/ReviewDTO.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewBoardServlet.java
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/mypage/membermypagereview.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
[ksk] 좋아요 기능 추가중 2025-03-04
- accountNickName -> accountNickname 으로 수정
- 좋아요 기능 추가중
> [ksk] 좋아요 기능 추가중 2025-03-04

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
[cya] klassBoardUpdate 구현 commit
- 게시글, 사진 수정 시 기존 attach,mapping delete 후 insert 되도록 구현
- 클래스 테이블, 클래스예약일 테이블은 update 되도록 구현
> [cya] klassBoardUpdate 구현 commit

- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveListServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveUpdateServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/DeleteReportKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ApproveDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ReportDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ApproveSerview.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ReportService.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/vo/Approve.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/vo/ReportKlass.java
- lumodiem/src/main/resources/mappers/approve-mapper.xml
- lumodiem/src/main/resources/mappers/report-mapper.xml
- lumodiem/src/main/webapp/views/admin/approveDetail.jsp
- lumodiem/src/main/webapp/views/admin/reportKlass.jsp
[ 추가 작업 ]
신고글 검색 및 삭제 기능
클래스 o
리뷰 x
리뷰 댓글 x
대기중인 클래스 테일블 옆 버튼 (승인,반려)x
> Kty 신고 클래스 기능 검색까지 완료

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/DeleteReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
- 리뷰 게시글 삭제 페이지 완성
- 리뷰 게시글 수정 페이지 작성중
> Lyj 리뷰게시글 삭제 페이지 완성

- lumodiem/src/main/java/com/lumodiem/account/controller/AccountCreateEndServlet.java
- lumodiem/src/main/webapp/views/account/create.jsp
[ksk] 주소 API 추가 완료 2025-03-04
- DB klass_date, reservation 테이블의 FK들 DELETE NO ACTION / 그 외 테이블들의 FK는 DELETE ON CASCADE 설정
- 주소 API 추가 완료
> [ksk] DB 수정. 주소 API 추가 완료 2025-03-04

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/resources/mybatis-config.xml
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
- DB klass_date, reservation 테이블의 FK들 DELETE NO ACTION / 그 외 테이블들의 FK는 DELETE ON CASCADE 설정
- 주소 API 추가 완료
- review 좋아요 작업중
> [ksk] review 좋아요 작업중1 2025-03-04

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassLikeChangeServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewLikeChangeServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- lumodiem/src/main/webapp/views/mypage/mypagelike.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
[ksk] review, klass 좋아요 작업 완료 2025-03-05
- review 좋아요 완료
- klass 좋아요 완료
> [ksk] review, klass 좋아요 작업 완료 2025-03-05

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassReservationServelt.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassDate.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 클래스 예약 기능 추가중
- 클래스 매퍼 변경
- klassDatail.jsp 변경
> Lyj 클래스 예약 기능 추가중

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassReservationServelt.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Reservation.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 클래스 예약기능 추가
- 같은클래스 중복예약 가능(안되게 바꿀거임)
> Lyj 클래스예약 기능 추가

- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveListServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/DeleteReportKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/DeleteReportReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportReviewCmtServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ReportDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ApproveSerview.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ReportService.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/vo/ReportReview.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/vo/ReportReviewCmt.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/CreateCommentEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/ReviewCmt.java
- lumodiem/src/main/resources/mappers/approve-mapper.xml
- lumodiem/src/main/resources/mappers/comment-mapper.xml
- lumodiem/src/main/resources/mappers/report-mapper.xml
- lumodiem/src/main/webapp/views/admin/reportKlass.jsp
- lumodiem/src/main/webapp/views/admin/reportReview.jsp
- lumodiem/src/main/webapp/views/admin/reportReviewCmt.jsp
- lumodiem/src/main/webapp/views/admin/reportReviewDetail.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
> Kty 리뷰 댓글 기능 구현 [ 등록, 수정, 삭제 ]

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Klass.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardCreate.jsp
- 좋아요 순으로 정렬 추가
- klassBoardUpdate 쪽 오류메세지 부분 filedelete 위치 이동 수정 완료
> [cya] klassBoard 클래스 게시글 목록 정렬 조회 수정 완료 commit

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoardUpdate.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 클래스 게시글 상세페이지 내부 댓글 클릭시 해당 댓글(리뷰) 의 상세조회로 넘겨주기 구현
> [cya] klassBoardDetail.jsp 수정 commit

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassReservationServelt.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/DeleteReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/InsertReviewPageEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewBoardServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/UpdateReviewEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/UpdateReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
- lumodiem/src/main/webapp/views/review/updateReview.jsp
- 검색기능 select-option 으로 변경
- 정렬하기 기본 최신순으로 변경
- 정렬하기 좋아요순 추가
- ReviewVo searchTxt,searchType 추가
- 리뷰 업데이트 완료
- 이미지 O => X 완료
- 이미지 O => O 완료
- 이미지 X => X 완료
- 이미지 X => O 완료
- 리뷰게시글 추가 할때 이미지가 있을때,없을때 로 나눠서 insert
> Lyj 리뷰 게시글 업데이트 완료 , 리뷰 목록 조회 수정

- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/DeleteReportReviewCmtServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportReviewCmtServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ReportDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ReportService.java
- lumodiem/src/main/resources/mappers/report-mapper.xml
- lumodiem/src/main/webapp/views/admin/reportReviewCmt.jsp
관리자 페이지 -완-
리뷰 댓글 기능 90% ( 신고x )
> [kty] 리뷰 댓글 삭제 기능 구현(상세x)

- lumodiem/src/main/java/com/lumodiem/board/adminboard/vo/ReportReview.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewBoardServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewReportServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
- 신고 버튼눌렀을때 부트스트랩으로 `모달` 나오게 함
- 리뷰리폿Vo 에 reportReviewTxt 추가
- 리뷰매퍼에 reportReview 추가
> Lyj 리뷰 신고 기능추가

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardListServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardUpdateEndServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Klass.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardUpdate.jsp
- 부트스트랩 반영하여 클래스 게시글의 목록을 출력
- 게시글의 사진이 있을때 사진 노출, 없으면 noImage 노출 -> 나중에 고정 이미지 넣을 예정
- 게시글 목록에는 작성자의 닉네임, 좋아요 갯수, 현재참여인원/최대참여가능 인원으로 노출.
- 게시글 하단의 더보기... <a>태그를 클릭시 해당 게시글 상세 페이지로 이동함.
> [cya] 클래스 게시판 목록 bootstrap 반영 수정 완료 commit

- lumodiem/src/main/java/com/lumodiem/account/controller/LoginEndServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/SearchIdServlet.java
- lumodiem/src/main/webapp/views/account/create.jsp
- lumodiem/src/main/webapp/views/account/login.jsp
- lumodiem/src/main/webapp/views/account/loginFail.jsp
- lumodiem/src/main/webapp/views/account/resetPwSetPw.jsp
- lumodiem/src/main/webapp/views/account/resetPwSetPwEndSuccess.jsp
- lumodiem/src/main/webapp/views/css/nav.css
- lumodiem/src/main/webapp/views/include/nav.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- lumodiem/src/main/webapp/views/mypage/hostmypageapproveklass.jsp
- lumodiem/src/main/webapp/views/mypage/hostmypagereview.jsp
- lumodiem/src/main/webapp/views/mypage/mypageDelete.jsp
- lumodiem/src/main/webapp/views/mypage/mypageUpdate.jsp
- lumodiem/src/main/webapp/views/mypage/mypageUpdateEnd.jsp
[ksk] 클래스 게시판 채팅방 작업 완료. 비밀번호 보이기/숨기기 토글 완료 2025-03-06
- klass -> chat 새로운 klass 생성시 새로운 chat 생성되게 트리거 설정.
- chat 테이블의 account_no 제거
- 클래스 채팅방 작업 완료.
- 비밀번호 보이기/숨기기 토글 완료
- 마이페이지 모든 클래스, 리뷰, 댓글 이동 가능하게 기능 추가
> [ksk] 클래스 게시판 채팅방 작업 완료. 비밀번호 보이기/숨기기 토글 완료 2025-03-06

- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 게시글 상세 조회 페이지에서 크게 나왔던 사진 사이즈 조정함
> [cya] klassDetail.jsp 부분수정 commit

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassReportServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassReport.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/resources/mybatis-config.xml
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- bootstrap 3, 5 충돌로 bootstrap 5버전으로 코드 변경 (성관님)
- 아직은 확정 단계 전이라 주석 처리
- klass-mapper 에 KlassReportVo 추가 , mybatis-config 수정
- klassDetail.jsp 많이 수정하여 conflict 예상
> [cya] 클래스 상세조회 페이지에 신고버튼 추가

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassReservationServelt.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassDate.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
- 중복예약 못하게 완료
- 남는자리 이상을 예약할때 못하게 완료
> Lyj 클래스 예약기능 완료

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassReservationServelt.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/KlassDate.java
> [lyj] 클래스 예약 세부조건 추가

- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/java/com/lumodiem/reviewfile/FilePathServlet.java
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
> Lyj 리뷰 목록조회 부트스트랩 추가

- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 채팅방 사이즈 변경 완료, 그림자로 입체감 더해줌
- 댓글창 테이블, 게시글 테이블 사이즈 일치하게 수정 완료
- 수정, 삭제, 예약, 예약 취소 버튼의 폰트색상은 미정.
> [cya] 클래스 게시글 상세조회 css 적용 완료 commit

- lumodiem/src/main/webapp/views/admin/reportKlass.jsp
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 클래스 목록에서 버튼과 인풋의 위치 조정, a 태그 밑줄 제거, 색상변경
- 신고된 클래스 목록에서 테이블의 색상, 틀 조정
- 검색창 위치, 스타일 조정 완료
> [cya] 클래스목록 , 신고된 클래스 목록 css 수정 commit

- lumodiem/src/main/webapp/views/admin/adminPage.jsp
- lumodiem/src/main/webapp/views/admin/reportList.jsp
- lumodiem/src/main/webapp/views/css/adminPage.css
- lumodiem/src/main/webapp/views/css/reviewCmtTest.css
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
> Kty css 입히는중 pr

- lumodiem/src/main/webapp/views/admin/reportKlass.jsp
- lumodiem/src/main/webapp/views/admin/reportReview.jsp
- lumodiem/src/main/webapp/views/admin/reportReviewCmt.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 신고된 클래스 목록, 리뷰 목록, 리뷰 댓글 목록의 css 조정
- 테이블의 색상, 틀, 인풋, 버튼 수정  
- summernote로 인해 txt 부분은 주석처리
- 해당 글 클릭시 reportKlassDetail로 가는 url을 klassDetail로 수정
- 위와 동일하게 reportReviewDetail로 가는 url을 reviewDetail로 수정
> [cya] 신고 목록 조회 페이지 css 수정 완료 commit

- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Klass.java
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/webapp/css/style.css
- lumodiem/src/main/webapp/index.jsp
- lumodiem/src/main/webapp/views/include/nav.jsp
- lumodiem/src/main/webapp/views/mypage/hostmypageapproveklass.jsp
- 마이페이지 전체 페이지 임시 css 적용완료.
- (create)
- (createSelect)
- (login)
- (loginFail)
- (mypageDelete)
- (mypageDeleteEndFail)
- (mypageDeleteSuccess)
- (resetPw)
- (resetPwSetPw)
- (resetPwSetPwEndSuccess)
- (searchId)
- (searchIdFail)
- (searchIdSuccess)
- 카카오 주소 API 기능 추가. 입력시 색상 추가
- 이메일 정규식 추가
- 참여자 참여 클래스 조회시 주소 추가
- 요구사항 정의서 완료
- nav 색상 추가
> [ksk] nav 색상 추가 2025-03-09

- lumodiem/src/main/webapp/views/admin/approveList.jsp
- lumodiem/src/main/webapp/views/admin/reportKlass.jsp
- lumodiem/src/main/webapp/views/admin/reportReview.jsp
- lumodiem/src/main/webapp/views/admin/reportReviewCmt.jsp
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- 대기 클래스 목록 작업완료(정렬 최신순 추후 확인해야함)
-신고 클래스목록 작업완료 (기능적 부분 피드백- 검색option에 제목, 	닉네임, 내용으로 되어있어 -> 클래스명,닉네임,신고사 
유 로 바꿈(이하  동일) + 신고사유로 검색 불가함)
- 신고 리뷰 목록 역시 신고사유로 검색 되지않음 확인
- 신고 리뷰댓글 목록은 검색 option에 신고 사유 자체가 없음 확인
- css부분만 작업 했기에 기능은 건드리지 않음.
> [cya] 관리자 페이지 목록 조회 css 수정 완료 commit

- lumodiem/src/main/java/com/lumodiem/common/controller/MainPageServlet.java
- lumodiem/src/main/webapp/index.jsp
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
- 리뷰 게시판의 검색창 하단으로 이동
- 작성하기 버튼과 정렬하기 드롭다운 위치 정렬 & 버튼 색상변경
- 리뷰 상세의 댓글 폼 변경, 버튼 색 변경
- reviewDetail 351줄 input type="button" 버튼 타입으로 바꿔야 하나 고려해볼 필요가있음
> [cya] 리뷰 게시판, 리뷰 상세글 css 수정 commit

- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/webapp/views/admin/adminPage.jsp
- lumodiem/src/main/webapp/views/admin/reportList.jsp
- lumodiem/src/main/webapp/views/mypage/membermypage.jsp
- 관리자 페이지 CSS 통일 완료
- 주최자 마이페이지 승인 대기중인 클래스 오름차순 완료
> [ksk]  관리자 페이지 CSS 완료 + 모든 페이지의 페이징 작업중 2025-03-10

- lumodiem/src/main/webapp/index.jsp
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardCreate.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardUpdate.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 홈화면 배경사진 삽입(index.jsp)
- 클래스 게시판에 사진 없을 시 대체할 썸네일 사진 반영.
- 클래스 상세조회에서 댓글 클릭시 리뷰 상세로 넘어가게 반영 완료.
- 클래스 게시글 작성, 수정 페이지의 작성 틀과 버튼 변경 반영 완료(스타일 조정)
> [cya] 클래스 게시판 관련 기능 수정 & css 조정 commit

- lumodiem/src/main/webapp/views/admin/approveDetail.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardCreate.jsp
- lumodiem/src/main/webapp/views/klass/klassBoardUpdate.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- lumodiem/src/main/webapp/views/review/insertReview.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
- lumodiem/src/main/webapp/views/review/updateReview.jsp
- 게시글(클래스, 리뷰) 작성/ 수정 부분의 버튼 위치, 여백 조정
- 승인 대기 클래스 목록 css 반영 완료(기능 확인은 아직)  -> 사진 여부는 아직 판단 안됨.
> [cya] 게시글 작성, 수정, 상세 페이지 css 조정 완료

- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassDetailServlet.java
- lumodiem/src/main/webapp/views/admin/approveDetail.jsp
- lumodiem/src/main/webapp/views/admin/approveList.jsp
- lumodiem/src/main/webapp/views/admin/reportReviewCmt.jsp
- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- lumodiem/src/main/webapp/views/review/reviewDetail.jsp
- 댓글 CSS, thead [번호] / 내용 / 닉네임
- 신고된 리뷰 목록 : 해당하는 리뷰로 이동하게 수정(업는 리뷰여서 홈화면으로 이동함)
- 승인 대기 클래스 목록 : 클래스 상세 목록에서 승인/반려 삭제 보이게 수정
-
> Kty 추가 수정 

- lumodiem/src/main/webapp/views/klass/klassDetail.jsp
- 작성된 리뷰가 없을 때 클릭시 오류페이지 발견-> 조건문으로 리뷰가 있는 경우만 클릭 되도록 수정.
> [cya] 클래스 상세조회 댓글 클릭시 반응 조건 수정 commit

- lumodiem/src/main/webapp/views/admin/reportReviewCmt.jsp
해당 리뷰 댓글이 없을때 삭제 버튼 위치 색 적용안된 거 색 꽉 채워지게 수정
> Kty 신고된 리뷰 댓글 테이블 색 조정

- lumodiem/src/main/resources/mappers/review-mapper.xml
> [lyj] 리뷰 목록 정렬수정

- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageApproveKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/HostMypageReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/MypageLikeKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/MypageLikeReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/account/dao/MypageDao.java
- lumodiem/src/main/java/com/lumodiem/account/service/MypageService.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/controller/KlassBoardListServlet.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/dao/HostBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/service/HostBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/hostboard/vo/Klass.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewBoardServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/controller/ReviewDetailServlet.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/dao/MemberBoardDao.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/service/MemberBoardService.java
- lumodiem/src/main/java/com/lumodiem/board/memberboard/vo/Review.java
- lumodiem/src/main/java/com/lumodiem/common/vo/Paging.java
- lumodiem/src/main/resources/mappers/klass-mapper.xml
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/resources/mappers/review-mapper.xml
- lumodiem/src/main/webapp/views/klass/klassBoard.jsp
- lumodiem/src/main/webapp/views/mypage/hostmypage.jsp
- lumodiem/src/main/webapp/views/mypage/hostmypageapproveklass.jsp
- lumodiem/src/main/webapp/views/mypage/mypagecmt.jsp
- lumodiem/src/main/webapp/views/mypage/mypagelikeklass.jsp
- lumodiem/src/main/webapp/views/mypage/mypagelikereview.jsp
- lumodiem/src/main/webapp/views/review/reviewBoard.jsp
[ksk]  관리자 페이지 CSS 완료 + 모든 페이지의 페이징 작업중7 2025-03-10
- 관리자 페이지 CSS 통일 완료
- 주최자 마이페이지 승인 대기중인 클래스 오름차순 완료
- review board 페이징 적용 완료
- klass board 페이징 적용완료
- review board 페이징 적용완료
- host, member mypage 페이징 적용완료
- admin mypage 작업중
> [ksk]  관리자 페이지 CSS 완료 + 모든 페이지의 페이징 작업중7 2025-03-10

- lumodiem/src/main/java/com/lumodiem/account/controller/MemberMypageKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/MemberMypageReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/MypageCmtServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/MypageLikeKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/account/controller/MypageLikeReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/account/dao/MypageDao.java
- lumodiem/src/main/java/com/lumodiem/account/service/MypageService.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportKlassServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ReportDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ReportService.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/vo/ReportKlass.java
- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/resources/mappers/report-mapper.xml
- lumodiem/src/main/webapp/views/admin/reportKlass.jsp
- lumodiem/src/main/webapp/views/mypage/membermypage.jsp
- lumodiem/src/main/webapp/views/mypage/membermypageklass.jsp
- lumodiem/src/main/webapp/views/mypage/membermypagereview.jsp
- lumodiem/src/main/webapp/views/mypage/mypagecmt.jsp
- lumodiem/src/main/webapp/views/mypage/mypagelikeklass.jsp
- lumodiem/src/main/webapp/views/mypage/mypagelikereview.jsp
- 관리자 페이지 CSS 통일 완료
- 주최자 마이페이지 승인 대기중인 클래스 오름차순 완료
- review board 페이징 적용 완료
- klass board 페이징 적용완료
- review board 페이징 적용완료
- host, member mypage 페이징 적용완료
- admin mypage 작업중
> [ksk]  관리자 페이지 CSS 완료 + 모든 페이지의 페이징 작업중8 2025-03-10

- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ApproveListServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/controller/ReportReviewServlet.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ApproveDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/dao/ReportDao.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ApproveSerview.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/service/ReportService.java
- lumodiem/src/main/java/com/lumodiem/board/adminboard/vo/ReportReview.java
- lumodiem/src/main/resources/mappers/approve-mapper.xml
- lumodiem/src/main/resources/mappers/report-mapper.xml
- lumodiem/src/main/webapp/views/admin/approveList.jsp
- lumodiem/src/main/webapp/views/admin/reportList.jsp
- lumodiem/src/main/webapp/views/admin/reportReview.jsp
- 관리자 페이지 CSS 통일 완료
- 주최자 마이페이지 승인 대기중인 클래스 오름차순 완료
- review board 페이징 적용 완료
- klass board 페이징 적용완료
- review board 페이징 적용완료
- host, member mypage 페이징 적용완료
- admin mypage 작업중
> [ksk]  페이징 작업 완료 2025-03-10

- lumodiem/src/main/resources/mappers/mypage-mapper.xml
- lumodiem/src/main/webapp/views/admin/reportReview.jsp
- lumodiem/src/main/webapp/views/mypage/membermypagereview.jsp
- mapper SQL문 오류 수정
- 신고된 리뷰글 클릭시 해당 상세 리뷰로 이동
> [ksk] 마이페이지 댓글 조회 오류 수정

- lumodiem/src/main/webapp/views/mypage/hostmypagereview.jsp
[ksk] 주최자 리뷰 페이지 2025-03-16
- 리뷰가 있음에도 리뷰와 함께 리뷰가 없습니다. 출력 오류 수정
> [ksk] 주최자 리뷰 페이지 2025-03-16
